#! /usr/bin/env python
# ------------------------------------------------------------------------------
# Project : __PP_NAME_BIG__                                        /          \
# Filename: pybaker.py                                            |     ()     |
# Date    : __PP_DATE__                                           |            |
# Author  : __PP_AUTHOR__                                         |   \____/   |
# License : __PP_LICENSE_NAME__                                    \          /
# ------------------------------------------------------------------------------

"""
A simple script to call the real pybaker.py
DO NOT EDIT THIS FILE UNLESS YOU ARE PREPARED FOR THE CONSEQUENCES!!!
"""

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

# system imports
from pathlib import Path
import shlex
import subprocess


# ------------------------------------------------------------------------------
# The main method of the program
# ------------------------------------------------------------------------------
def main():
    """
    The main method of the program

    This method is the main entry point for the program, initializing the
    program, and performing its steps.
    """

    # path to dev pyplate src pybaker.py
    p_pb_real = Path.home() / "__PP_DEV_PP__" / "__PP_SUPPORT__" / "pybaker.py"
    s_pb_real = str(p_pb_real)

    # get current path
    curr_path = Path(__file__).resolve()

    # call real pybaker with current path on cmd line
    cmd = f"{s_pb_real} {curr_path}"
    cmd_array = shlex.split(cmd)

    # get result of running the shell command
    subprocess.run(cmd_array, check=True)


# ------------------------------------------------------------------------------
# Code to run when called from command line
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    # Code to run when called from command line

    # This is the top level code of the program, called when the Python file is
    # invoked from the command line.

    # run main function
    main()

# -)
