#! /usr/bin/env python
# ------------------------------------------------------------------------------
# Project : PyPlate                                                /          \
# Filename: pybaker.py                                            |     ()     |
# Date    : 04/19/2024                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

"""
A simple script to call the real pybaker.py
DO NOT EDIT THIS FILE UNLESS YOU ARE PREPARED FOR THE CONSEQUENCES!!!
"""

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

# system imports
from pathlib import Path
import shlex
import subprocess


# ------------------------------------------------------------------------------
# The main method of the program
# ------------------------------------------------------------------------------
def main():
    """
    The main method of the program

    This method is the main entry point for the program, initializing the
    program, and performing its steps.
    """

    # path to dev pyplate src pybaker.py
    # TODO: text replacement or val if we can find dict in private
    p_pb_real = Path.home() / "__PC_PYBAKER__"
    s_pb_real = str(p_pb_real)

    # get current path
    curr_path = Path(__file__)

    # call real pybaker with current path on cmd line
    cmd = f"{s_pb_real} {curr_path}"
    cmd_array = shlex.split(cmd)

    # get result of running the shell command
    subprocess.run(cmd_array, check=True)


# ------------------------------------------------------------------------------
# Code to run when called from command line
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    # Code to run when called from command line

    # This is the top level code of the program, called when the Python file is
    # invoked from the command line.

    # run main function
    main()

# -)
