# ------------------------------------------------------------------------------
# Project : GUIs_DEBUG                                             /          \
# Filename: pyproject.toml                                        |     ()     |
# Date    : 09/29/2024                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

[build-system]
requires = ["setuptools>=59.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "__PP_NAME_SMALL__"
version = "__PP_VERSION__"
description = "__PP_SHORT_DESC__"
authors = [{ name = "__PP_AUTHOR__", email = "__PP_EMAIL__" }]
readme = "__PP_README_FILE__"
license = { file = "__PP_LICENSE_FILE__" }
keywords = [__PP_KW_STR__]
classifiers = [
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
# NB: dependencies in pyproject.toml are WAY too complicated for an automaton,
# and are best handled manually (ie. you're on your own here, bud...)
dependencies = []

[project.urls]
homepage = "__PP_URL__/__PP_NAME_BIG__"

# -)
