# ------------------------------------------------------------------------------
# Project : __PC_NAME_BIG__                                        /          \
# Filename: pyproject.toml                                        |     ()     |
# Date    : __PC_DATE__                                           |            |
# Author  : __PD_AUTHOR__                                         |   \____/   |
# License : __PD_LICENSE_NAME__                                    \          /
# ------------------------------------------------------------------------------

[build-system]
requires = ["setuptools>=59.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
# some of these values will be replaced by either pymaker.py or pybaker.py
# they are only here to satisfy the linter
name = "__PC_NAME_SMALL__"
version = "__PM_VERSION__"
description = "__PC_SHORT_DESC__"
authors = [{ name = "__PD_AUTHOR__", email = "__PD_EMAIL__" }]
readme = "__PD_README_FILE__"
license = { file = "__PD_LICENSE_FILE__" }
classifiers = [
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []
dependencies = []
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/__PD_AUTHOR__/__PC_NAME_BIG__"

# -)
